### ISSUE TITLE
stopSampleSound() is undefined

### ISSUE THREAD

**Issue by luhoaegona** [saadqbal/react-native-notification-sounds#11]
i don't have find function stopSampleSound.

**Comment by saadqbal** [comment]
Please make sure you are using the latest version. also make sure you have imported the stopSampleSound like this:

```javascript
import NotificationSounds, { playSampleSound, stopSampleSound } from 'react-native-notification-sounds';
```

**Comment by luhoaegona** [comment]
hello @saadqbal , when i using version 0.2.4 it have sound but when i upgrade to 0.5.0, not have sound.

**Comment by saadqbal** [comment]
Make sure you are testing it on real device if its iOS. 

Please look into this repo for sample implementation: https://github.com/saadqbal/notificationSounds

**Comment by luhoaegona** [comment]
yes i using real device ( i using android ), if i using 0.2.4 it working and if 0.5.0 not working.
i have change version 2 times, and when using 0.2.4 it alway work, when 0.5.0 alway not working.

**Comment by saadqbal** [comment]
Please check the sample and see if that works for you.

Do the following on your project as well:
1. change react-native-notification-sounds version to **0.5.2** in your **package** file. 
2. remove **node_modules** folder
3. **npm install** or **yarn**

**Comment by luhoaegona** [comment]
oke thanks, it working but only sound when i on sound in app not sound notification. i see version 0.2.4 it have sound alway i not turn sound app. And other question, i want customer sound with my list sound, i have list : 
const [dataSound, setDataSound] = useState([{
        soundID: 1,
        title: 'Nokia',
        url: 'soundnokia.mp3'
    },
    {
        soundID: 2,
        title: 'Office',
        url: 'soundoffice.mp3'
    },
    {
        soundID: 3,
        title: 'Jarvis',
        url: 'soundjarvis.mp3'
    }]);

but when i play it not working.

Thanks.
