### ISSUE TITLE
Need to change index.d.ts

### ISSUE THREAD

**Issue by MoronovArt** [saadqbal/react-native-notification-sounds#13]
declare module "react-native-notification-sounds" {
export interface Sound {
  soundID: string
  url: string
  title: string
}

export function playSampleSound(s: Sound): void
export function stopSampleSound(): void

type TNotificationSounds = { getNotifications(type: string): Promise<Sound[]> };

const NotificationSounds: TNotificationSounds;
export default NotificationSounds;
}

**Comment by saadqbal** [comment]
Hi @MoronovArt ,
 Thank you for the suggestion? Could you please mention what have you changed and why it needs to be changed?

**Comment by MoronovArt** [comment]
TS2693: 'Promise' only refers to a type, but is being used as a value here
at line NotificationSounds.getNotifications

**Comment by saadqbal** [comment]
Thank you @MoronovArt.
