### ISSUE TITLE
A problem occurred configuring project ':react-native-notification-sounds'. > com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

### ISSUE THREAD

**Issue by mazcodep** [saadqbal/react-native-notification-sounds#24]
A problem occurred configuring project ':react-native-notification-sounds'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

**Comment by mobeenali12** [comment]
Hi @mazcodep , were you able to find the solution for this?

**Comment by saadqbal** [comment]
This has now been resolved in the latest release.
