### ISSUE TITLE
Sound duration

### ISSUE THREAD

**Issue by xcarpentier** [saadqbal/react-native-notification-sounds#4]
This is a feature request for adding sound duration into this module when getting all systems sounds.

I found another package that used AV kit I guess : https://github.com/zmxv/react-native-sound/blob/3fe5480fce935e888d5089d94a191c7c7e3aa190/RNSound/RNSound.m#L224

Do you think it’s possible ?

**Comment by xcarpentier** [comment]
Or maybe it will be good to return a RN promise like this post talk about, that way we are able to manage playing in a loop.

https://stackoverflow.com/questions/14121612/audioservicesplaysystemsound-know-when-sound-stopped

**Comment by xcarpentier** [comment]
Or add add a loop function

**Comment by saadqbal** [comment]
Hey @xcarpentier, I will be happy to merge your pull request if you have solve it.
