### ISSUE TITLE
Sound List is empty on IOS devices.

### ISSUE THREAD

**Issue by beingArkReal** [saadqbal/react-native-notification-sounds#9]
I'm having trouble with ios devices where I can't load any sound list whereas on android everything works smoothly.

` "react-native-notification-sounds": "^0.2.2",
   "react": "16.9.0",
    "react-native": "0.61.5",
`

`   "device_details" : {
        "os_version" : "13.3",
        "device_model" : "iPhone XR"
    },`

**Comment by saadqbal** [comment]
Make sure you are testing it on real iOS device. iOS emulator does not have sound files.
